import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Spanish translations for all namespaces
const spanishTranslations = {
  "common": {
    "save": "Guardar",
    "cancel": "Cancelar",
    "delete": "Eliminar",
    "edit": "Editar",
    "close": "Cerrar",
    "loading": "Cargando...",
    "error": "Error",
    "success": "Éxito",
    "confirm": "Confirmar",
    "back": "Atrás",
    "next": "Siguiente",
    "submit": "Enviar",
    "clear": "Limpiar",
    "search": "Buscar",
    "filter": "Filtrar",
    "export": "Exportar",
    "import": "Importar",
    "download": "Descargar",
    "upload": "Subir",
    "copy": "Copiar",
    "paste": "Pegar",
    "cut": "Cortar",
    "undo": "Deshacer",
    "redo": "Rehacer",
    "select": "Seleccionar",
    "selectAll": "Seleccionar todo",
    "deselectAll": "Deseleccionar todo"
  },
  "auth": {
    "signIn": "Iniciar sesión con Google",
    "signOut": "Cerrar sesión",
    "authRequired": "Se requiere autenticación para usar esta aplicación",
    "tokenExpired": "Tu sesión ha expirado. Por favor inicia sesión nuevamente.",
    "welcomeBack": "¡Bienvenido de nuevo!",
    "signInPrompt": "Iniciar sesión para continuar",
    "signInRequired": "Debes iniciar sesión para usar esta función",
    "signingIn": "Iniciando sesión...",
    "signingOut": "Cerrando sesión...",
    "researchAgent": "Agente de Investigación",
    "tagline": "Asistente de investigación con IA",
    "secureAuth": "Autenticación segura con tecnología de Google"
  },
  "chat": {
    "placeholder": "Escribe tu mensaje aquí...",
    "send": "Enviar",
    "retry": "Reintentar",
    "stop": "Detener",
    "thinking": "Pensando...",
    "generating": "Generando respuesta...",
    "newChat": "Nuevo Chat",
    "clearHistory": "Limpiar Historial",
    "loadChat": "Cargar Chat",
    "systemPrompt": "Indicación del Sistema",
    "customInstructions": "Instrucciones Personalizadas",
    "temperature": "Temperatura",
    "maxTokens": "Tokens Máximos",
    "model": "Modelo",
    "provider": "Proveedor",
    "history": "Historial de Chat",
    "continue": "Continuar",
    "regenerate": "Regenerar",
    "edit": "Editar",
    "delete": "Eliminar",
    "copy": "Copiar",
    "copied": "¡Copiado!",
    "selectFiles": "Seleccionar Archivos",
    "attachFiles": "Adjuntar Archivos",
    "pasteImage": "Pegar Imagen",
    "recording": "Grabando...",
    "voiceInput": "Entrada de Voz",
    "stopRecording": "Detener Grabación",
    "processing": "Procesando...",
    "noMessages": "No hay mensajes aún. ¡Inicia una conversación!",
    "clearConfirm": "¿Estás seguro de que quieres limpiar todos los mensajes?",
    "deleteConfirm": "¿Estás seguro de que quieres eliminar este mensaje?",
    "loadingHistory": "Cargando historial de chat...",
    "savingChat": "Guardando chat...",
    "chatSaved": "Chat guardado exitosamente",
    "chatLoaded": "Chat cargado exitosamente",
    "errorSaving": "Error al guardar el chat",
    "errorLoading": "Error al cargar el chat",
    "signInRequired": "Por favor inicia sesión para usar esta función",
    "providerRequired": "Por favor configura al menos un proveedor en Configuración",
    "messageError": "Error al enviar el mensaje",
    "streamError": "Error en el flujo del mensaje",
    "toolExecution": "Ejecutando herramienta...",
    "toolExecuted": "Herramienta ejecutada exitosamente",
    "toolError": "Error de ejecución de herramienta",
    "searchingWeb": "Buscando en la web...",
    "scrapingContent": "Extrayendo contenido...",
    "transcribingAudio": "Transcribiendo audio...",
    "generatingImage": "Generando imagen...",
    "generatingChart": "Generando gráfico...",
    "executingCode": "Ejecutando código...",
    "planningMode": "Modo de Planificación",
    "exitPlanning": "Salir de Planificación",
    "startPlanning": "Iniciar Planificación",
    "mcpServers": "Servidores MCP",
    "addMCPServer": "Agregar Servidor MCP",
    "mcpServerName": "Nombre del Servidor",
    "mcpServerUrl": "URL del Servidor",
    "exampleServers": "Servidores de Ejemplo",
    "officialServers": "Servidores MCP Oficiales",
    "sampleServers": "Servidores de Muestra",
    "instructions": "Instrucciones",
    "availableTools": "Herramientas Disponibles",
    "enableServer": "Habilitar Servidor",
    "disableServer": "Deshabilitar Servidor",
    "removeServer": "Eliminar Servidor",
    "serverAdded": "Servidor agregado exitosamente",
    "serverRemoved": "Servidor eliminado exitosamente",
    "invalidUrl": "Formato de URL inválido",
    "nameRequired": "Se requiere el nombre del servidor",
    "urlRequired": "Se requiere la URL del servidor",
    "chatHistory": "Historial de Chat",
    "examples": "Ejemplos",
    "attachContext": "Adjuntar Contexto",
    "attachContextTooltip": "Adjunta fragmentos de la base de conocimiento como contexto para esta conversación",
    "searchProvider": "Proveedor de Búsqueda:",
    "functionCall": "Llamada de Función:",
    "code": "Código:",
    "arguments": "Argumentos:",
    "callId": "ID de Llamada:",
    "result": "Resultado:",
    "url": "URL:",
    "viewRawHtml": "Ver HTML sin procesar sin comprimir",
    "copyOutputToClipboard": "Copiar salida al portapapeles",
    "copyCodeToClipboard": "Copiar código al portapapeles",
    "captureToSwag": "Capturar a Swag",
    "captureOutputToSwag": "Capturar salida a Swag",
    "captureCodeToSwag": "Capturar código a Swag",
    "grabImage": "Capturar imagen",
    "noSummarization": "Sin resumen",
    "usingProxy": "Usando proxy para mayor privacidad y evasión de detección de bots",
    "contentExtracted": "Contenido extraído inteligentemente",
    "truncatedToFit": "Truncado para ajustarse al modelo",
    "scrapeMethod": "Método de Extracción:",
    "tier": "Nivel",
    "scrapeTime": "Tiempo de Extracción:",
    "totalTime": "Tiempo Total:",
    "format": "Formato:",
    "originalSize": "Tamaño Original:",
    "compressedSize": "Tamaño Comprimido:",
    "compression": "Compresión:",
    "compressionStrategy": "Estrategia de Compresión:",
    "basicExtraction": "Extracción básica",
    "rawHtml": "HTML Sin Procesar ({{count}} caracteres)",
    "rawText": "Texto Sin Procesar ({{count}} caracteres)",
    "contentProcessingPipeline": "Pipeline de Procesamiento de Contenido:",
    "size": "Tamaño:",
    "titlePrompt": "Título/Indicación",
    "finalPrompt": "Indicación Final",
    "deleteChat": "Eliminar Chat",
    "clearAllChats": "Limpiar Todos los Chats",
    "confirmClearAll": "¿Estás seguro de que quieres limpiar todo el historial de chat?",
    "confirmDelete": "¿Estás seguro de que quieres eliminar este chat?",
    "noChatsYet": "No hay chats aún",
    "startChatting": "Comienza a chatear para ver el historial aquí",
    "chatDeleted": "Chat eliminado",
    "allChatsCleared": "Todos los chats limpiados",
    "chatTitle": "Título del Chat",
    "enterChatTitle": "Ingresa un título para este chat...",
    "signInToChat": "Por favor inicia sesión para comenzar a chatear",
    "streamingResponse": "Respuesta en transmisión...",
    "imageAddedToSwag": "¡Imagen agregada a Swag!",
    "imageAddedWithoutConversion": "¡Imagen agregada a Swag (sin conversión)!",
    "contentCapturedToSwag": "¡Contenido capturado a Swag!",
    "contentCapturedWithoutConversion": "¡Contenido capturado a Swag (sin conversión de imagen)!",
    "planningTransferred": "Indicaciones de planificación transferidas a nuevo chat",
    "failedToTransfer": "Error al transferir datos de planificación",
    "addedToPlaylist": "{{count}} video{{plural}} agregado{{plural}} a la lista de reproducción",
    "transcriptionStopped": "Transcripción detenida",
    "failedToStopTranscription": "Error al detener la transcripción: {{error}}",
    "fileTypeNotSupported": "Tipo de archivo no compatible: {{name}}. Tipos compatibles: JPEG, PNG, GIF, WebP, PDF",
    "fileTooLarge": "Archivo demasiado grande: {{name}} ({{size}}MB). Tamaño máximo: {{maxSize}}MB",
    "imageTokenWarning": "La imagen {{name}} puede usar muchos tokens (~{{tokens}}k). Considera usar una imagen más pequeña.",
    "fileAdded": "{{name}} agregado",
    "failedToProcess": "Error al procesar {{name}}",
    "signInToSendMessages": "Por favor inicia sesión para enviar mensajes",
    "foundRelevantChunks": "🔍 Se encontraron {{count}} fragmentos relevantes de la base de conocimiento",
    "noRelevantContext": "No se encontró contexto relevante en la base de conocimiento",
    "failedToRetrieveRag": "Error al recuperar el contexto RAG, continuando sin él",
    "sessionExpired": "Tu sesión ha expirado. Por favor inicia sesión nuevamente.",
    "todoLimitReached": "Límite de progresión automática de tareas alcanzado. Por favor continúa manualmente.",
    "snippetSaved": "Fragmento guardado: {{title}}",
    "snippetDeleted": "Fragmento eliminado: {{title}}",
    "copiedToClipboard": "¡Copiado al portapapeles!",
    "outputCopied": "¡Salida copiada al portapapeles!",
    "codeCopied": "¡Código copiado al portapapeles!",
    "inputPlaceholder": "Escribe tu mensaje... (Shift+Enter para nueva línea, ↑↓ para historial)",
    "continueProcessing": "Continuar Procesamiento",
    "stopGenerating": "Detener generación de respuesta",
    "sendMessage": "Enviar mensaje",
    "chatMessageInput": "Entrada de mensaje de chat",
    "editPlan": "Editar Plan",
    "makeAPlan": "Hacer un Plan",
    "close": "Cerrar",
    "failedToLoadChat": "Error al cargar el chat",
    "mcpServerNamePlaceholder": "Nombre del Servidor (ej., filesystem, github)",
    "mcpServerUrlPlaceholder": "URL del Servidor (ej., http://localhost:3000)",
    "noMcpServers": "No hay servidores MCP configurados",
    "addServer": "Agregar Servidor",
    "remove": "Eliminar",
    "chatHistoryTitle": "Historial de Chat",
    "noChatHistory": "No se encontró historial de chat. Inicia una conversación para guardarla automáticamente.",
    "allChatHistoryCleared": "Todo el historial de chat limpiado",
    "loadChatSuccess": "Chat cargado exitosamente",
    "examplesTitle": "Ejemplos de Chat",
    "tryExample": "Prueba este ejemplo",
    "attachContextTitle": "Adjuntar Contexto de Swag",
    "snippetsAttached": "{{count}} fragmento{{plural}} adjunto{{plural}}",
    "attachSnippets": "Adjuntar Fragmentos",
    "searchSnippets": "Buscar fragmentos...",
    "selectAll": "Seleccionar Todo",
    "selectNone": "Seleccionar Ninguno",
    "deleteSelected": "Eliminar Seleccionados",
    "cancel": "Cancelar",
    "load": "Cargar",
    "confirmDeleteChat": "¿Estás seguro de que quieres eliminar este chat?",
    "confirmClearHistory": "¿Estás seguro de que quieres limpiar todo el historial de chat?",
    "confirmDeleteSelected": "¿Estás seguro de que quieres eliminar {{count}} chat{{plural}} seleccionado{{plural}}?",
    "chatLoadedFrom": "Cargado desde",
    "chatSavedAt": "Guardado en",
    "noTitle": "Sin título",
    "clearAttachedSnippets": "Limpiar todos los fragmentos adjuntos",
    "mcpServerConfiguration": "Configuración del Servidor MCP",
    "typeMessageFirst": "Escribe un mensaje primero",
    "typeMessage": "Escribe un mensaje",
    "signInToSend": "Por favor inicia sesión para enviar mensajes"
  },
  "planning": {
    "title": "Planificación de Investigación",
    "query": "Consulta de Investigación",
    "generatePlan": "Generar Plan",
    "savePlan": "Guardar Plan",
    "loadSaved": "Cargar Guardado",
    "transferToChat": "Transferir al Chat",
    "clearAll": "Limpiar Todo",
    "debug": "Depurar",
    "planning": "Planificando...",
    "planGenerated": "Plan generado exitosamente",
    "noPlan": "Aún no se ha generado ningún plan",
    "enterQuery": "Ingresa tu consulta o tema de investigación...",
    "researchFocus": "Enfoque de Investigación",
    "methodology": "Metodología",
    "expectedOutcome": "Resultado Esperado",
    "initializing": "Inicializando...",
    "processing": "Procesando...",
    "signInToGenerate": "Inicia sesión para Generar Plan",
    "generating": "Generando...",
    "signInToUsePlanning": "Por favor inicia sesión para usar la planificación",
    "signInRequired": "Por favor inicia sesión con Google para usar la función de planificación",
    "authExpired": "Autenticación expirada. Por favor cierra sesión e inicia sesión nuevamente para continuar.",
    "authRequired": "Se requiere autenticación. Por favor inicia sesión con Google para continuar.",
    "enterResearchQuestion": "Por favor ingresa una pregunta de investigación",
    "debugCopied": "¡Información de depuración copiada al portapapeles!",
    "debugCopyFailed": "Error al copiar información de depuración",
    "savePlanTooltip": "Guarda el plan actual en tu lista de planes guardados",
    "loadSavedPlans": "Cargar Planes Guardados",
    "debugTooltip": "Copiar información de depuración para solución de problemas de Copilot",
    "transferTooltip": "Transferir al Chat",
    "clearAllTooltip": "Limpiar todos los datos de planificación y comenzar de nuevo",
    "systemPromptEditable": "Indicación del Sistema Generada (Editable):",
    "systemPromptHelp": "Esto define el rol y comportamiento de la IA. Edítalo según sea necesario antes de transferir al chat.",
    "userQueryEditable": "Consulta de Usuario Generada (Editable):",
    "userQueryHelp": "Este es el mensaje que se enviará al chat. Edítalo para refinar tu consulta.",
    "generatedPrompts": "Indicaciones Generadas",
    "llmInfoTooltip": "Ver información de transparencia del LLM (modelo, tokens, costo)",
    "llmCalls": "llamada",
    "llmCallsPlural": "llamadas",
    "cannotSavePlan": "No se puede guardar el plan: No se generó un plan válido",
    "planSavedSuccess": "Plan guardado exitosamente",
    "planSaveFailed": "Error al guardar el plan",
    "loadSavedPlan": "Cargar Plan Guardado",
    "storage": "Almacenamiento",
    "storageWarning": "El almacenamiento está al {{percentage}}% de su capacidad",
    "storageWarningHelp": "Considera eliminar planes antiguos para liberar espacio.",
    "noSavedPlans": "No se encontraron planes guardados",
    "saved": "Guardado",
    "load": "Cargar",
    "simpleQueryDetected": "Consulta Simple Detectada",
    "simpleQueryHelp": "Esta consulta puede responderse directamente sin planificación extensa.",
    "comprehensiveResearchPlan": "📚 Plan de Investigación Completo",
    "analysisSummary": "📊 Resumen del Análisis",
    "queryType": "Tipo de Consulta:",
    "complexity": "Complejidad:",
    "researchApproach": "Enfoque de Investigación:",
    "estimatedSources": "Fuentes Estimadas:",
    "reasoning": "Razonamiento:",
    "expertPersona": "🎭 Persona Experta",
    "searchQueries": "🔍 Consultas de Búsqueda:",
    "researchQuestions": "📋 Preguntas de Investigación:",
    "suggestedSources": "🌐 Fuentes Sugeridas:",
    "sources": "Fuentes:",
    "variousRelevantSources": "Varias fuentes relevantes",
    "researchMethodology": "⚙️ Metodología de Investigación:",
    "enhancedSystemPrompt": "🤖 Indicación del Sistema Mejorada:",
    "enhancedUserPrompt": "💬 Indicación de Usuario Mejorada:",
    "debugRawLlmResponse": "🔍 Depurar: Campos de Respuesta Bruta del LLM",
    "longFormDocumentPlan": "📝 Plan de Documento de Formato Largo",
    "longFormNote": "Nota: Esto se construirá en etapas usando fragmentos. Cada sección se investigará y escribirá por separado, luego se combinará en un documento final.",
    "documentStructure": "📑 Estructura del Documento:",
    "keywords": "Palabras Clave:",
    "workflow": "⚙️ Flujo de Trabajo:",
    "needMoreInfo": "❓ Se Necesita Más Información",
    "pleaseClarify": "Por favor aclara:",
    "updateQueryDetails": "Actualiza tu consulta con más detalles:",
    "provideMoreDetails": "Proporciona detalles más específicos...",
    "regeneratePlanWithClarifications": "Regenerar Plan con Aclaraciones",
    "moreInfoRequired": "📋 Se Requiere Más Información",
    "planType": "Tipo de Plan:",
    "detectedComplexityPatterns": "🔍 Patrones de Complejidad Detectados:",
    "estimatedIterations": "Iteraciones Estimadas",
    "toolsRequired": "Herramientas Requeridas",
    "suggestedWorkflow": "⚙️ Flujo de Trabajo Sugerido:",
    "requiredTools": "🛠️ Herramientas Requeridas:",
    "guidanceQuestions": "💡 Por favor responde estas preguntas para refinar tu plan:",
    "updatePromptWithAnswers": "Actualiza tu indicación de investigación con las respuestas:",
    "guidanceTip": "💡 Consejo: Incluye las respuestas a las preguntas anteriores en tu consulta actualizada. Cuanto más específico seas, mejor podrá la IA crear un plan de múltiples iteraciones efectivo con el uso apropiado de herramientas y ejemplos de pocos disparos.",
    "guidanceExamplePlaceholder": "Ejemplo: Quiero construir un informe de investigación completo sobre el cambio climático:\n1. Creando 25 tareas para diferentes subtemas (política, ciencia, economía, etc.)\n2. Buscando en la web para cada tema y guardando los resultados en fragmentos\n3. Generando gráficos para visualizar puntos de datos clave\n4. Combinando todos los fragmentos en un análisis maestro\n\nPor favor crea un plan detallado con ejemplos de pocos disparos que muestren cómo usar create_todo, search_web, create_snippet y generate_chart juntos en cada iteración...",
    "generateDetailedExecutionPlan": "🎯 Generar Plan de Ejecución Detallado",
    "forcePlan": "⚡ Forzar Plan",
    "forcePlanTooltip": "Deja que la IA responda las preguntas y fuerce la generación del plan",
    "reset": "🔄 Reiniciar",
    "resetTooltip": "Limpiar modo de guía y volver al estado anterior",
    "aboutGuidanceMode": "Acerca del Modo de Guía:",
    "guidanceModeHelp": "Este modo detecta proyectos complejos que requieren múltiples iteraciones y uso extensivo de herramientas. Responde las preguntas anteriores para ayudar a crear un plan de ejecución detallado con ejemplos de pocos disparos que muestren cómo usar tareas, fragmentos y múltiples llamadas de herramientas por iteración.",
    "forcingPlan": "Forzando generación del plan...",
    "forcePlanError": "Error al forzar el plan",
    "forcePlanFailed": "Falló al forzar el plan",
    "clarificationAnswer": "Por favor usa tu mejor criterio basándote en la consulta original."
  },
  "settings": {
    "title": "Configuración",
    "language": "Idioma",
    "selectLanguage": "Seleccionar Idioma",
    "providers": "Proveedores",
    "cloudSync": "Sincronización en la Nube",
    "billing": "Facturación",
    "general": "General",
    "generalDescription": "Configura ajustes generales de la aplicación incluyendo idioma y preferencias de visualización",
    "languageHelp": "Cambia el idioma de la interfaz e instruye a la IA para responder en tu idioma seleccionado",
    "providerCredentials": "Credenciales de Proveedor",
    "providerDescription": "Configura tus claves API de proveedor LLM. El backend selecciona automáticamente el mejor modelo para cada solicitud",
    "modelSelectionStrategy": "Estrategia de Selección de Modelo",
    "modelStrategyDescription": "Elige cómo el sistema selecciona modelos para tus solicitudes. Esto equilibra costo, calidad y rendimiento",
    "cheap": "Económico (Recomendado)",
    "cheapDescription": "Prioriza proveedores gratuitos (Groq, Gemini) y modelos más pequeños capaces. Recurre a proveedores de pago solo cuando esté limitado por tasa. Mejor para la mayoría de los casos de uso",
    "balanced": "Equilibrado",
    "balancedDescription": "Elige modelos que hagan el trabajo de manera confiable sin comprometer la calidad. Usa nivel gratuito cuando la calidad es equivalente, modelos de pago cuando la calidad importa. Equilibra costo vs. capacidad",
    "powerful": "Potente",
    "powerfulDescription": "Usa los mejores modelos disponibles (GPT-4o, Gemini 2.5 Pro, o1) para máxima capacidad. Prioriza calidad sobre costo. Usa modelos de razonamiento para análisis complejo",
    "fastest": "Más Rápido",
    "fastestDescription": "Prioriza modelos de baja latencia (Groq) para respuestas rápidas. Puede sacrificar algo de calidad por velocidad en solicitudes simples. Excelente para sesiones interactivas",
    "tavilyApiKey": "Clave API de Tavily (Opcional)",
    "tavilyPlaceholder": "tvly-...",
    "tavilyHelp": "Habilita búsqueda y extracción web mejorada a través de la API de Tavily. Recurre a DuckDuckGo si no se proporciona",
    "enabledTools": "Herramientas Habilitadas",
    "webSearch": "Búsqueda Web",
    "webSearchDescription": "Busca en la web información actual, noticias y artículos",
    "executeJs": "Ejecución de JavaScript",
    "executeJsDescription": "Ejecuta código JavaScript para cálculos y procesamiento de datos",
    "scrapeUrl": "Extracción Web",
    "scrapeUrlDescription": "Extrae contenido de URLs y sitios web específicos",
    "youtubeSearch": "Búsqueda en YouTube",
    "youtubeDescription": "Busca videos en YouTube con soporte de transcripción",
    "transcribe": "Transcribir Audio/Video",
    "transcribeDescription": "Convierte archivos de audio y video a transcripciones de texto",
    "generateChart": "Generar Gráficos",
    "chartDescription": "Crea visualizaciones y gráficos a partir de datos",
    "generateImage": "Generar Imágenes",
    "imageDescription": "Crea imágenes generadas por IA a partir de descripciones de texto",
    "searchKnowledgeBase": "Buscar en Base de Conocimiento",
    "ragDescription": "Busca en documentos cargados y base de conocimiento",
    "manageTodos": "Gestionar Tareas",
    "todosDescription": "Crea y gestiona listas de tareas y recordatorios",
    "manageSnippets": "Gestionar Fragmentos",
    "snippetsDescription": "Guarda y recupera fragmentos de código y texto",
    "askLlm": "Preguntar a LLM",
    "askLlmDescription": "Delega sub-preguntas a otras instancias de LLM",
    "generateReasoning": "Generar Cadena de Razonamiento",
    "reasoningDescription": "Razonamiento analítico paso a paso para problemas complejos",
    "proxySettings": "Configuración de Proxy",
    "proxyDescription": "Configura proxy HTTP/HTTPS para solicitudes web",
    "enableProxy": "Habilitar Proxy",
    "proxyUrl": "URL del Proxy",
    "proxyUrlPlaceholder": "http://proxy.example.com:8080",
    "proxyUsername": "Usuario (Opcional)",
    "proxyPassword": "Contraseña (Opcional)",
    "locationServices": "Servicios de Ubicación",
    "locationDescription": "Usa tu ubicación para resultados de búsqueda localizados e información específica de la región",
    "enableLocation": "Habilitar Servicios de Ubicación",
    "locationHelp": "Permite que las búsquedas web devuelvan resultados localmente relevantes",
    "currentLocation": "Ubicación Actual",
    "requestLocation": "Solicitar Ubicación",
    "clearLocation": "Limpiar Ubicación",
    "locationPermission": "Permiso de Ubicación",
    "permissionGranted": "Concedido",
    "permissionDenied": "Denegado",
    "permissionPrompt": "No solicitado",
    "tabs": {
      "general": "General",
      "provider": "Proveedor",
      "cloud": "Sincronización en la Nube",
      "tools": "Herramientas",
      "proxy": "Proxy",
      "location": "Ubicación",
      "tts": "TTS",
      "rag": "RAG"
    },
    "appearance": "Apariencia",
    "theme": "Tema",
    "darkMode": "Modo Oscuro",
    "lightMode": "Modo Claro",
    "notifications": "Notificaciones",
    "privacy": "Privacidad",
    "accessibility": "Accesibilidad",
    "fontSize": "Tamaño de Fuente",
    "lineHeight": "Altura de Línea"
  },
  "languages": {
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
    "zh": "中文",
    "ja": "日本語",
    "ar": "العربية",
    "nl": "Nederlands",
    "pt": "Português",
    "ru": "Русский"
  },
  "billing": {
    "title": "Panel de Facturación",
    "balance": "Saldo de Crédito",
    "totalCost": "Costo Total",
    "totalTokens": "Tokens Totales",
    "totalRequests": "Solicitudes Totales",
    "cost": "Costo",
    "tokens": "Tokens",
    "tokensIn": "Tokens Entrantes",
    "tokensOut": "Tokens Salientes",
    "timestamp": "Marca de Tiempo",
    "noTransactions": "Aún no hay transacciones",
    "creditsPurchased": "Créditos comprados exitosamente",
    "insufficientCredits": "Créditos insuficientes",
    "purchaseCredits": "Agregar Crédito",
    "amount": "Monto",
    "paymentMethod": "Método de Pago",
    "transactions": "Transacciones",
    "overview": "Resumen",
    "exportCSV": "Exportar CSV",
    "clearData": "Limpiar Datos",
    "clearDataConfirm": "¿Estás seguro de que quieres limpiar los datos de facturación?",
    "dataClearedSuccess": "✅ Éxito: Se limpiaron {{count}} transacciones. {{remaining}} restantes.",
    "dataClearError": "❌ Error: {{message}}",
    "noDataToExport": "No hay datos para exportar",
    "startDate": "Fecha de Inicio",
    "endDate": "Fecha de Fin",
    "type": "Tipo",
    "provider": "Proveedor",
    "model": "Modelo",
    "duration": "Duración",
    "status": "Estado",
    "allTypes": "Todos los Tipos",
    "allProviders": "Todos los Proveedores",
    "clearFilters": "Limpiar Filtros",
    "quickRanges": "Rangos rápidos:",
    "today": "Hoy",
    "last7Days": "Últimos 7 Días",
    "last30Days": "Últimos 30 Días",
    "thisMonth": "Este Mes",
    "byType": "Por Tipo",
    "byProvider": "Por Proveedor",
    "byModel": "Por Modelo",
    "requests": "Solicitudes",
    "groupByRequestId": "📦 Agrupar por ID de Solicitud",
    "itemsPerPage": "por página",
    "totalRequestGroups": "{{count}} grupos de solicitudes totales (mostrando {{showing}}), {{ungrouped}} sin agrupar",
    "totalTransactionsShowing": "{{total}} transacciones totales (mostrando {{showing}})",
    "requestGroup": "🔗 Grupo de Solicitudes ({{count}} transacciones)",
    "signInRequired": "🔐 Se Requiere Inicio de Sesión",
    "signInToViewBilling": "Por favor inicia sesión con Google para ver tus datos de facturación.",
    "howToAccessBilling": "📋 Cómo Acceder a los Datos de Facturación:",
    "signInStep1": "Haz clic en el botón \"Iniciar sesión con Google\" en la barra de navegación superior",
    "signInStep2": "¡Eso es todo! Tus datos de facturación se cargarán automáticamente",
    "billingDataNote": "💡 Tus datos de facturación se almacenan en una Hoja de cálculo de Google de cuenta de servicio centralizada y se recuperan automáticamente. No se necesitan permisos adicionales ni acceso a Drive - solo inicia sesión con Google.",
    "debugInfo": "🔧 Información de Depuración",
    "loading": "Cargando datos de facturación...",
    "errorLoading": "⚠️ Error al Cargar Datos de Facturación",
    "retry": "🔄 Reintentar",
    "noBillingData": "No hay datos de facturación disponibles. Por favor espera...",
    "noTransactionsMessage": "No se encontraron transacciones",
    "noBillingDataYet": "📊 Aún No Hay Datos de Facturación",
    "startUsingChat": "Comienza a usar el chat para generar registros de facturación. Todo el uso de API se rastrea automáticamente.",
    "refresh": "🔄 Actualizar",
    "usageOnly": "Solo uso (excl. créditos)",
    "totalCredits": "Créditos Totales",
    "userQueries": "Consultas de Usuario",
    "llmCalls": "Llamadas LLM",
    "userQueriesLlmCalls": "Consultas de Usuario / Llamadas LLM",
    "newBalance": "Nuevo saldo:",
    "creditsToAdd": "Créditos a agregar:",
    "minimumPurchase": "La compra mínima es $5.00",
    "addCreditsTitle": "💳 Agregar Créditos",
    "purchaseCreditsDescription": "Compra créditos para usar funciones de IA. Compra mínima: $5.00",
    "enterAmount": "Ingresa el monto (mín $5.00)",
    "tipUseOwnKeys": "💡 Consejo: ¡Agrega tus propias claves API en Configuración para costos LLM de $0! Solo se aplican costos de infraestructura cuando usas tus propias claves.",
    "loadingPayPal": "Cargando PayPal...",
    "paypalNotLoaded": "⚠️ SDK de PayPal no cargado. Por favor actualiza la página.",
    "close": "Cerrar",
    "clearBillingData": "Limpiar Datos de Facturación",
    "clearDataWarning": "⚠️ Advertencia: Esta acción no se puede deshacer. Tus datos de facturación se eliminarán permanentemente.",
    "clearAll": "Limpiar Todo",
    "clearByProvider": "Limpiar por Proveedor",
    "clearByDateRange": "Limpiar por Rango de Fechas",
    "clearAllDescription": "Esto eliminará todas las transacciones de tu hoja de facturación.",
    "considerExportFirst": "Considera exportar a CSV primero para tus registros.",
    "selectProvider": "Seleccionar Proveedor:",
    "selectProviderPlaceholder": "-- Seleccionar Proveedor --",
    "clearProviderHint": "Útil para alinearse con los ciclos de facturación del proveedor (ej., limpiar mensualmente).",
    "clearDateRangeHint": "Dejar en blanco para limpiar desde el principio/hasta el final. Ambos pueden usarse juntos.",
    "confirmUndoCheckbox": "Entiendo que esta acción no se puede deshacer",
    "cancel": "Cancelar",
    "page": "Página",
    "of": "de",
    "first": "⏮️ Primera",
    "prev": "◀️ Anterior",
    "next": "Siguiente ▶️",
    "last": "Última ⏭️",
    "types": {
      "chat": "Chat",
      "embedding": "Incrustación",
      "guardrail_input": "🛡️ Entrada de Guardarraíl",
      "guardrail_output": "🛡️ Salida de Guardarraíl",
      "planning": "Planificación",
      "assessment": "Evaluación",
      "image_generation": "🖼️ Generación de Imagen",
      "tts": "🎙️ Texto a Voz",
      "chat_iteration": "Iteración de Chat",
      "credit_added": "Crédito Agregado",
      "summary": "Resumen",
      "lambda_invocation": "Invocación Lambda"
    }
  },
  "errors": {
    "generic": "Ocurrió un error",
    "network": "Error de red",
    "timeout": "Tiempo de espera agotado",
    "unauthorized": "Acceso no autorizado",
    "forbidden": "Acceso prohibido",
    "notFound": "Recurso no encontrado",
    "serverError": "Error del servidor",
    "validationError": "Error de validación",
    "tryAgain": "Por favor intenta nuevamente"
  },
  "swag": {
    "title": "Base de Conocimiento",
    "newSnippet": "Nuevo Fragmento",
    "editSnippet": "Editar Fragmento",
    "deleteSnippet": "Eliminar Fragmento",
    "searchSnippets": "Buscar fragmentos...",
    "noSnippets": "No se encontraron fragmentos",
    "tags": "Etiquetas",
    "addTag": "Agregar Etiqueta",
    "removeTag": "Eliminar Etiqueta",
    "filterByTag": "Filtrar por Etiqueta",
    "content": "Contenido",
    "created": "Creado",
    "modified": "Modificado",
    "source": "Fuente"
  },
  "tts": {
    "readAloud": "Leer en Voz Alta",
    "stopReading": "Detener Lectura",
    "pauseReading": "Pausar Lectura",
    "resumeReading": "Reanudar Lectura",
    "voice": "Voz",
    "speed": "Velocidad",
    "volume": "Volumen",
    "provider": "Proveedor de TTS"
  },
  "playlist": {
    "title": "Lista de Reproducción",
    "addToPlaylist": "Agregar a Lista de Reproducción",
    "removeFromPlaylist": "Eliminar de Lista de Reproducción",
    "playNext": "Reproducir Siguiente",
    "playNow": "Reproducir Ahora",
    "clearPlaylist": "Limpiar Lista de Reproducción",
    "emptyPlaylist": "La lista de reproducción está vacía"
  },
  "tools": {
    "search": "Búsqueda Web",
    "scrape": "Extraer Contenido",
    "transcribe": "Transcribir",
    "youtube": "YouTube",
    "javascript": "Ejecutar JavaScript",
    "generateChart": "Generar Gráfico",
    "generateImage": "Generar Imagen"
  }
};

// Write to file
const outputPath = path.join(__dirname, '..', 'src', 'i18n', 'locales', 'es.json');
fs.writeFileSync(outputPath, JSON.stringify(spanishTranslations, null, 2), 'utf8');

console.log('✅ Spanish translation file created successfully!');
console.log(`📁 Output: ${outputPath}`);
