name: Deploy UI

on:
  push:
    branches: [main]
    paths:
      - 'ui-new/**'
      - 'scripts/build-docs.sh'
      - 'scripts/deploy-docs.sh'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui-new/package-lock.json
      
      - name: Install UI dependencies
        run: |
          cd ui-new
          npm ci
      
      - name: Build React UI
        run: |
          chmod +x scripts/build-docs.sh
          ./scripts/build-docs.sh
      
      - name: Deploy to GitHub Pages
        run: |
          chmod +x scripts/deploy-docs.sh
          
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Deploy (script handles git add/commit/push)
          ./scripts/deploy-docs.sh --build -m "docs: auto-deploy UI from GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Summary
        run: |
          echo "## UI Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ UI successfully deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: https://syntithenai.github.io/lambdallmproxy/" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: main" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
