name: Deploy Lambda

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        description: 'Deployment type'
        required: true
        type: choice
        options:
          - fast
          - full
        default: 'fast'
      deploy_env:
        description: 'Also deploy environment variables'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
      
      - name: Deploy Lambda (Fast)
        if: inputs.deployment_type == 'fast'
        run: |
          chmod +x scripts/deploy-fast.sh
          ./scripts/deploy-fast.sh
      
      - name: Deploy Lambda (Full)
        if: inputs.deployment_type == 'full'
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
      
      - name: Deploy Environment Variables
        if: inputs.deploy_env == true
        run: |
          chmod +x scripts/deploy-env.sh
          
          # Create .env.lambda from secrets
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > .env.lambda
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.lambda
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env.lambda
          echo "GOOGLE_SHEETS_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SHEETS_SERVICE_ACCOUNT_EMAIL }}" >> .env.lambda
          echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> .env.lambda
          echo "GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" >> .env.lambda
          echo "AUTHORIZED_USERS=${{ secrets.AUTHORIZED_USERS }}" >> .env.lambda
          echo "LAMBDA_PROFIT_MARGIN=${{ secrets.LAMBDA_PROFIT_MARGIN || '6' }}" >> .env.lambda
          echo "PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}" >> .env.lambda
          echo "PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}" >> .env.lambda
          
          # Deploy to Lambda
          ./scripts/deploy-env.sh --yes
      
      - name: Summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Type**: ${{ inputs.deployment_type }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment Variables**: ${{ inputs.deploy_env && 'Updated' || 'Not updated' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Region**: ${{ secrets.AWS_REGION || 'us-east-1' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
